### ISSUE TITLE
Don't transmit to Honeycomb without an API key

### ISSUE THREAD

**Issue by martinjt** [honeycombio/libhoney-dotnet#12]
Question is what to do... Throw an exception when registering into DI, or throw a warning? or throw a warning and drop the packets on send.

**Comment by lizthegrey** [comment]
Our other libraries will print the traces to stdout if you don't supply an API key...

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now as we're moving more towards supporting OpenTelemetry SDKs. Feel free to re-open if it’s still relevant.
