### ISSUE TITLE
The term TeamId is confusing

### ISSUE THREAD

**Issue by irvingpop** [honeycombio/libhoney-dotnet#14]
@danyelf and I noticed when doing some usability testing that people were easily confused by the term `TeamId` when all they had was a write key

**Comment by martinjt** [comment]
Have you got a suggestion based on the other beelines?  Maybe use "API Key"?

**Comment by danyelf** [comment]
I think `write_key` is the way we do it in other beelines.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now as we're moving more towards supporting OpenTelemetry SDKs. Feel free to re-open if it’s still relevant.

**Comment by MikeGoldsmith** [comment]
Reopening as it would be nice to deprecate TeamId and add WriteKey for consistency.
