### ISSUE TITLE
Default SendFrequency is probably wrong

### ISSUE THREAD

**Issue by twpol** [honeycombio/libhoney-dotnet#16]
The `SendFrequency` value is clearly milliseconds, looking at the examples and code using it, however, the default value is `60`:

https://github.com/martinjt/honeycomb/blob/f7075175ed69f17741f5165d836ec1e35a49b54e/src/Honeycomb/Models/HoneycombApiSettings.cs#L27

I can't help but feel that 60ms is not what was intended here. I have a terminal with trace logging spamming messages:

```
trce: Microsoft.Extensions.Hosting.BackgroundService[0]
      Starting Flush
trce: Honeycomb.HoneycombService[0]
      Flushing honeycomb events
trce: Microsoft.Extensions.Hosting.BackgroundService[0]
      Delaying for 60
trce: Microsoft.Extensions.Hosting.BackgroundService[0]
      Starting Flush
trce: Honeycomb.HoneycombService[0]
      Flushing honeycomb events
trce: Microsoft.Extensions.Hosting.BackgroundService[0]
      Delaying for 60
```

**Comment by martinjt** [comment]
That's perfectly valid.  As it's override in appsettings, etc. I hadn't considered it.  I'll need to have a think about the impact of changing the default.  I think it should probably be the same as the default in the docs `10000`
