### ISSUE TITLE
X-Honeycomb-Team not set

### ISSUE THREAD

**Issue by jwj** [honeycombio/libhoney-dotnet#17]
When giving an instance of HoneycombApiSettings in a ASP.NET core application, the X-Honeycomb-Team is not set in the HTTP header (inspected using Fiddler).
```
services.AddHoneycomb(new HoneycombApiSettings {
						TeamId = "xyz",
						DefaultDataSet = "abc",
						BatchSize = 1,
						SendFrequency = 5000,
				});
```
However, putting the settings in appsettings works:
```
services.AddHoneycomb(Configuration);
```

**Comment by martinjt** [comment]
Thanks for reporting this, it should definitely work.  I'll take a look
tonight.

**Comment by martinjt** [comment]
I think I've got this, it was a misunderstanding of mapping IOptions.  I'll hopefully have a new version out tomorrow.
