### ISSUE TITLE
Possible to make work on .net framework  ?

### ISSUE THREAD

**Issue by leethomascook** [honeycombio/libhoney-dotnet#7]
Hi,

Great project. We have a few legacy applications which still use .net framework (4.7.2), and some dependencies prevent us from going up to .net core.

I can see how I can make the simple use case work with .net framewor by using the service directly, but doing it out of the bounds of the web request seems a bit more tricky. Happy to have a go a contributing something ( if worthwhile). Do you have any thoughts on how to do that? Send messages to a queue (e.g azure queue) and then have a function / webjob process them? Or am I over complicating it?

Thanks,

Lee

**Comment by martinjt** [comment]
It was specifically done as dotnet core to save time, but 4.7.2 might be doable for the service part which is netstandard2.0.

The main thing to do is think about "what" creates the initial event "where" it's stored (i.e. the context) and "how" someone adds to that context's event.

I'm not sure what the "out of the bounds of a web request" means though.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now as we're moving more towards supporting OpenTelemetry SDKs. Feel free to re-open if it’s still relevant.
