### ISSUE TITLE
.Net Core Hosted Service?

### ISSUE THREAD

**Issue by jkdey** [honeycombio/libhoney-dotnet#8]
Does this support use in a .net Core Hosted service? If not, what kind of work would be required to use this for a .Net Core Hosted service (e.g. non-Http, or mix of Http and non-Http traffic)

**Comment by martinjt** [comment]
There are 2 main components to the library.

1. The client library
2. The AspNet Extension

The client library just queues and sends events when it's told to flush.  This will work anywhere, but you'll need to manually fire the flush action.

The AspNet extension provides to interactivity APIs for creating an event context (in this case per-request), and an ability for you to add your data to that request.  It then queues this in the above client library.  Additionally, it includes a service that tells the client library to flush periodically.

So, in answer to the question, you'll be able to run it, and the AspNet extension will flush events on an interval.  What you'll need to do is create an event at the right time yourself, and push that to the `IHoneycombService` when you've finished adding your data to the event.

The biggest hurdle is always working out what tie your "context" to.  In things that run on a schedule, it's the "run", for things that run in response to an external stimulus, it's that.  For web, it's really easy, as you have the HttpContext, and the "Request".

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now as we're moving more towards supporting OpenTelemetry SDKs. Feel free to re-open if it’s still relevant.
